---
 title: "COTAN documentation"
 output:
   html_document:
     css: html-md-01.css
     fig_caption: no
     number_sections: no
     toc: no
     toc_float: false
     collapsed: no
---

```{r set-options, echo=FALSE}
 options(width = 105)
 knitr::opts_chunk$set(dev='png', dpi=300, cache=T)
 #pdf.options(useDingbats = TRUE)
```

# Overview

This web page contains all data regarding the COTAN paper. Here can be found:

* All datasets analysis, some of which with and whitout initial cleaning step. 

* The comparison of our gene clustering to detect cortex layer markers, with the markers found in Loo et al. paper. This part also contains the comparison with a WGCNA approach.

* The negative dataset analysis.\\

* **The repository for the package tool is the [gitHub](https://github.com/seriph78/COTAN).**

# Datasets

In this work where use the following public datasets:

- Mouse embryonic cortex dataset with four time points of development: E11.5 (GSM2861510), E13.5 (GSM2861511), E15.5 (GSE107122), E17.5 (GSM2861514). This study was performed by the Drop-seq scRNAseq technology.
- Mouse dentate gyrus dataset (GSE104323) with many different time points of development but, for this study, only the E16.5 was used. This study was performed using the 10X platform.
- Mouse embryonic cortex dataset (GSE123335) with two time points of development: E14.5 and P0. In this case the method used was Drop-seq.

# Computation time 
The COTAN analysis time is approximatively proportional to the cell number in the dataset. In particular, the most demanding step is the analysis step when a is minimized for each gene. This step is done by a multicore function (that is not supported under windows architecture). By default, and during tests it was fixed to 11 cores.
For example, a dataset with around 5000 cells was analysed in around 3 minutes. The machine used had RAM 64GiB and an Intel(R) Dual Xeon(R) Silver 4214 CPU @ 2.20GHz. 

* For more details see the [specific page](https://seriph78.github.io/Cotan_paper/Execution_times.nb.html).



