---
title: "Loo et all markers"
output:
     html_notebook:
      css: html-md-01.css
      fig_caption: yes
      highlight: haddock
      number_sections: yes
      theme: spacelab
      toc: yes
      toc_float: true
      collapsed: no
---
```{r}
input_dir = "../../Cotan_paper/Data/"
layers = list("L1"=c("Reln","Lhx5"), "L2/3"=c("Satb2","Cux1"), "L4"=c("Rorb","Sox5") , "L5/6"=c("Bcl11b","Fezf2") , "Prog"=c("Vim","Hes1"))
#objE17 = readRDS(file = paste(input_dir,"E17.5_cortex.cotan.RDS", sep = ""))
objE17 = readRDS(file = paste(input_dir,"E17.5_cortex_cleaned.cotan.RDS", sep = ""))
```

```{r}
g.space = get.gene.coexpression.space(objE17, 
                                      n.genes.for.marker = 28,  
                                      primary.markers = unlist(layers))
```
```{r}
g.space = as.data.frame(as.matrix(g.space))

coex.pca.genes <- prcomp(t(g.space),
                 center = TRUE,
                 scale. = F) 

fviz_eig(coex.pca.genes, addlabels=TRUE,ncp = 10)
#fviz_eig(coex.pca.genes, choice = "eigenvalue", addlabels=TRUE)
```
Hierarchical clustering
```{r}

# clustering usign Ward method
hc.norm = hclust(dist(g.space), method = "ward.D2")

# and cut the tree into 5 clusters (for example)
cut = cutree(hc.norm, k = 7, order_clusters_as_data = F)

# It crates the tree
dend <- as.dendrogram(hc.norm)

# I can use a dataframe from the pca to store some data regarding the clustering
pca_1 = as.data.frame(coex.pca.genes$rotation[,1:5])
pca_1 = pca_1[order.dendrogram(dend),]


mycolours <- c("genes related to L5/6" = "#3C5488FF","genes related to L2/3"="#F39B7FFF","genes related to Prog"="#4DBBD5FF","genes related to L1"="#E64B35FF","genes related to L4" = "#91D1C2FF", "not marked"="#B09C85FF")

# save the cluster number into the dataframe
pca_1$hclust = cut

dend =branches_color(dend,k=7,col=c("#4DBBD5FF","#91D1C2FF","#F39B7FFF","#E64B35FF","#3C5488FF","#91D1C2FF","#B09C85FF" ),groupLabels = T)
#dend =color_labels(dend,k=5,labels = rownames(pca_1),col=pca_1$colors)



dend %>%
set("labels", ifelse(labels(dend) %in% rownames(pca_1)[rownames(pca_1) %in% unlist(layers)], labels(dend), "")) %>%
  set("branches_k_color", value = c("gray80","#4DBBD5FF","#91D1C2FF" ,"gray80","#F39B7FFF","#E64B35FF","#3C5488FF"), k = 7) %>%
plot(horiz=F, axes=T,ylim = c(0,80))
```



```{r}
Markers_Loo = read.csv("Data/Markers_Loo.csv")
```

```{r}
genes_detected = pca_1[rownames(pca_1) %in% unlist(Markers_Loo)[!unlist(Markers_Loo) == ""],]

```

Gene present in the 10% of most differentially expressed genes by COTAN
```{r}
dim(genes_detected)[1]
```

of total genes detected as markers by Loo et al
```{r}
length(unlist(Markers_Loo)[!unlist(Markers_Loo) == ""])
```

Number of genes detected:
```{r}
sum(unlist(Markers_Loo)[!unlist(Markers_Loo) == ""] %in% rownames(objE17@coex))
```
Removed becouse not detected
```{r}
pure.markers = unlist(Markers_Loo)
pure.markers = pure.markers[!unlist(Markers_Loo) == ""]
pure.markers[!pure.markers %in% rownames(objE17@coex)]
```
```{r}
Markers_Loo = as.list(Markers_Loo)
for (i in names(Markers_Loo)) {
    Markers_Loo[[i]] = Markers_Loo[[i]][! Markers_Loo[[i]] == ""]
}
Markers_Loo
```

Table

```{r}
tableMarkersCOTAN = as.data.frame(matrix(nrow = 6,ncol = 4))
colnames(tableMarkersCOTAN)=c("Loo.L.I","Loo.L.II.IV","Loo.L.V.VI","Loo.PROG")
rownames(tableMarkersCOTAN)=c("COTAN.L.I","COTAN.L.II.III","COTAN.L.IV","COTAN.L.V.VI","COTAN.PROG","COTAN.Not Groupped")

layers.cluster = c("Reln","Satb2","Rorb","Bcl11b","Vim")
names(layers.cluster) = unique(cut[unlist(layers)])
layers.cluster
```


```{r}
groups = list("L.I"=5,"L.II.III"=4,"L.IV"=7,"L.V.VI"=6,"PROG"=2)

for(layer1 in c("L.I","L.II.III", "L.IV","L.V.VI","PROG")){
    for(layer2 in c("L.I","L.II.IV","L.V.VI","PROG")){
    tableMarkersCOTAN[paste0("COTAN.",layer1),paste0("Loo.",layer2)] =
        sum(rownames(pca_1[pca_1$hclust %in% groups[[layer1]],]) %in% Markers_Loo[[layer2]])
    tableMarkersCOTAN[paste0("COTAN.","Not Groupped"),paste0("Loo.",layer2)] =
        sum(rownames(pca_1[!pca_1$hclust %in% unlist(groups),]) %in% Markers_Loo[[layer2]])
    }
}

tableMarkersCOTAN
```


```{r}
specific.genes.table = data.frame("genes"=c(), "COTAN"=c(),"Loo."=c())
tt1 = c()
tt2 = c()
for(layer1 in c("L.I","L.II.III", "L.IV","L.V.VI","PROG")){
    for(layer2 in c("L.I","L.II.IV","L.V.VI","PROG")){
    tt1 = data.frame("genes"= rownames(pca_1[pca_1$hclust %in% groups[[layer1]],])[rownames(pca_1[pca_1$hclust 
                          %in% groups[[layer1]],]) %in% Markers_Loo[[layer2]]])
    if (dim(tt1)[1] > 0) {
                   tt1 = cbind(tt1,  "COTAN"=layer1, "Loo."=layer2)
        }
    tt2 = data.frame("genes"= 
        rownames(pca_1[!pca_1$hclust %in% unlist(groups),])[rownames(pca_1[!pca_1$hclust %in%                   unlist(groups),]) %in% Markers_Loo[[layer2]]])
    if (dim(tt2)[1] > 0) {
        tt2 = cbind(tt2, "COTAN"= "Not Groupped", "Loo."=layer2)
    }
    specific.genes.table = rbind(specific.genes.table,tt1,tt2)
    }
}

specific.genes.table[!(duplicated(specific.genes.table)) , ]

```
```{r fig.height= 80, fig.width= 8}
dend %>%
set("labels", ifelse(labels(dend) %in% rownames(pca_1)[rownames(pca_1) %in% specific.genes.table$genes], labels(dend), "")) %>%
  set("branches_k_color", value = c("gray80","#4DBBD5FF","#91D1C2FF" ,"gray80","#F39B7FFF","#E64B35FF","#3C5488FF"), k = 7) %>%
    plot(horiz=T, axes=T,xlim = c(0,80),cex = 1)

```



