---
title: "Synthetic dataset analysis"
output:
  html_notebook:
      css: html-md-01.css
      fig_caption: yes
      highlight: haddock
      number_sections: yes
      theme: spacelab
      toc: yes
      toc_float: true
      collapsed: no
---
```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = TRUE,
  warning = FALSE,
  tidy = TRUE, tidy.opts=list(width.cutoff=40)
)
options(rmarkdown.html_vignette.check_title = FALSE)
```
# Low  and high cell number simulated from a E17.5 neural cortex dataset (Drop-seq) and hippocampus P0 dataset (10X)

```{r include=FALSE}
library(COTAN)
library(scales)
library(stringr)
library(matrixStats)
library(latex2exp)
library(data.table)
library(ggplot2)
#source("../cotan01/src/cotan_output_functions.R")
```

```{r include=FALSE}
files = c("sym_E17_cl1_800cs/average",
          "sym_E17_cl1_4000cs/average",
          "sym_E17_cl6_4000cs/average",
          "sym_E17_cl6_800cs/average",
          "sym_P0_cl15_800cs/average",
          "sym_P0_cl15_4000cs/average") #


nu.tot.plot = data.frame("nu"=double() , "est"=double(), "group"=character(), "cells"=character(), "clusters"=character(), "method"=character())
lambda.tot.plot = data.frame("lambda_real"=double() , "lambda_est"=double(),"group"=character(), "cells"=character(), "clusters"=character(), "method"=character())
a_table = data.frame("average"=double(),"sqrt"=double())

for(tt in files ){
  input_dir = paste("Data/",tt,"/",sep = "")
  cl = strsplit(tt, "_")[[1]][3]
  col.a = strsplit(tt, "/")[[1]][2]
  for.raw = cl 
  if (cl == "cl1") {
    cond = "single"
    cl = "H"
  }else{
    cond = "multi"
    cl = "M"
  }
  #cl = paste(strsplit(cl, "l")[[1]][2],"cl.", sep = " ")
  method = strsplit(tt, "\\/|\\_| ")[[1]][2]
  if(method == "P0"){
    method = "10X"
  }else{
    method = "DSQ"
  }
  ncells = strsplit(strsplit(tt, "\\/|\\_| ")[[1]][4],"c")[[1]][1]
  
  row.a = paste(method, cl,ncells, sep = '_') 
  epo = strsplit(tt, "_")[[1]][2]
  
  if (epo == "E17") {
      eta = as.data.frame(fread("Data/input/eta_out17_average.csv", header = T))
      theta = as.data.frame(fread("Data/input/theta_out17_average.csv", header = T))
      nu.samples = read.csv("Data/input/nu_out17_average.csv", header = T,row.names = 1)
      
  }else if(epo == "P0"){
        eta = as.data.frame(fread("Data/input/eta_outP0_average.csv", header = T))
      theta = as.data.frame(fread("Data/input/theta_outP0_average.csv", header = T))
      nu.samples = read.csv("Data/input/nu_outP0_average.csv", header = T,row.names = 1)
  }
  colnames(eta) = eta[1,]
  genes = eta[2:nrow(eta),1]
  eta = eta[2:nrow(eta), 2:ncol(eta)]
  eta = as.data.frame(sapply(eta, as.numeric)) 
  rownames(eta) = genes    
  
  colnames(theta) = theta[1,]
  rownames(theta) = theta[,1]
  theta = theta[2:nrow(theta), 2:ncol(theta)]
  theta =  as.data.frame(sapply(theta, as.numeric)) 
  rownames(theta) = genes
  cl2 = unique(nu.samples$cluster)
  cl.perc = vector(length = length(cl2))
  names(cl.perc) = cl2
  for (c in cl2) {
     cl.perc[c] = length(nu.samples$cluster[nu.samples$cluster == c])/length(nu.samples$cluster)
  }
  sum(cl.perc)
  cluster.single = names(which(cl.perc == max(cl.perc)))
  real_lambda_multi = as.matrix(eta * theta)  %*% diag(cl.perc) 
  
  #real_lambda_multi = t(t(as.matrix(eta * theta)) * ((as.vector(cl.perc))))
  
  real_lambda_multi = rowSums(real_lambda_multi)
  real_lambda_single = eta[,cluster.single] * theta[,cluster.single]
   names(real_lambda_single)= rownames(eta)

  #cl = paste(strsplit(cl, "l")[[1]][2],"cl.", sep = " ")
  t = strsplit(tt, "/")[[1]][1]
  #lista = load_files2.0(input_dir = input_dir, t = t , s = "Sy2")
  
  #cells=lista[[2]] 
  cells= as.data.frame(fread(paste(input_dir,"cells_",t,".csv", sep = "")))
  rownames(cells)=cells$V1
  cells = as.matrix(cells[,2:ncol(cells)])
  
  #nu_est = lista[[3]]
  nu_est = read.csv(paste(input_dir,"nu_est_",t,".csv", sep = ""), row.names = 1)
  

  
  cells.for.raw = paste0(ncells,"cs.csv.gz")
  raw = as.data.frame(fread(paste("Data/simulated_datasets/simulated.dataset",epo,for.raw, cells.for.raw, 
                                  sep = "_")))
  rownames(raw)=raw$V1
  real_nu = raw[1,]
  raw = as.matrix(raw[2:nrow(raw),2:ncol(raw)])
  #raw_norm = lista[[4]] 
  raw_norm <- t(t(as.matrix(raw)) * (1/(as.vector(nu_est))))
  
  colnames(raw_norm)=colnames(cells)
  raw_norm = as.data.frame(raw_norm)
  
  #tot2 = lista[[5]]
  load(paste(input_dir,"a_minimization_",t, sep = ""))
  
  #lambda_i = lista[[7]]
  lambda_i = read.csv(paste(input_dir,"lambda_i_",t,".csv", sep = ""), row.names = 1)
  #real_nu = lista[[8]]
  print(paste("real nu", length(real_nu), sep = " "))
  #dsq.e14ctx = lista[[8]]
  #rm(lista)
  
  
  #print("a table")
  
  a_table[row.a,col.a] = sum(tot2$a < 0)/length(tot2$a)*100  
  
  #print("dataframe for nu")
  nu_est = as.array(nu_est$x)
  to.plot.nu = data.frame("nu"=t(real_nu[2:length(real_nu)]))
  #print(paste(length(nu_est), dim(to.plot.nu), sep = " "))
  to.plot.nu$est= nu_est
  to.plot.nu$group = rep(paste(c(row.a, col.a), collapse = '_'),nrow(to.plot.nu)) 
  to.plot.nu$cells = rep(ncells,nrow(to.plot.nu)) 
  to.plot.nu$clusters = rep(cl,nrow(to.plot.nu)) 
  to.plot.nu$method = rep(col.a,nrow(to.plot.nu)) 
  
  #print("dataframe for lambda")
  lambda_est = as.array(lambda_i$x)
  lambda_est = as.data.frame(lambda_i)
  if (cond == "multi") {
    to.plot.lambda = data.frame("lambda_real"= real_lambda_multi[rownames(cells)],
                                "lambda_est"=lambda_est[rownames(cells),1])
  }else if(cond == "single" ){
    to.plot.lambda = data.frame("lambda_real"= real_lambda_single[rownames(cells)], 
                                "lambda_est"=lambda_est[rownames(cells),1])
  }
  
  to.plot.lambda$group = rep(paste(c(row.a, col.a), collapse = '_') ,nrow(to.plot.lambda)) 
  to.plot.lambda$cells = rep(ncells,nrow(to.plot.lambda)) 
  to.plot.lambda$clusters = rep(cl,nrow(to.plot.lambda)) 
  to.plot.lambda$method = rep(col.a,nrow(to.plot.lambda)) 
  
  print("all dataframe formed")
  
  nu.tot.plot = rbind(nu.tot.plot,to.plot.nu) 
  lambda.tot.plot = rbind(lambda.tot.plot, to.plot.lambda)
  lambda.tot.plot = lambda.tot.plot[complete.cases(lambda.tot.plot),]
  
}

```

```{r}
mycolours <- c(
  "DSQ_H_4000_average"= "#E64B35FF" ,
  "DSQ_H_800_average" = "#4DBBD5FF" ,
  "DSQ_M_4000_average" = "#F39B7FFF"  ,
    "DSQ_M_800_average" = "#00A087FF",
  "10X_M_800_average" =  "#3C5488FF" ,
    "10X_M_4000_average"= "#8491B4FF" , 
  "DSQ_H_4000_sqrt"  = "#E64B35B2" ,
  "DSQ_H_800_sqrt"    ="#4DBBD5B2" ,
  "DSQ_M_4000_sqrt"   = "#F39B7FB2"  ,
  "DSQ_M_800_sqrt"    = "#00A087B2" ,
  "10X_M_800_sqrt"    = "#3C5488B2" ,
  "10X_M_4000_sqrt" = "#8491B4B2" 
  
  
  )

dodge <- position_dodge(width = 0.8)
  
si = 12
 nu= ggplot(nu.tot.plot,aes(x=cells, y=log(est)-log(nu), fill=group)) +
    facet_grid(method ~ ., scales = "free")+ 
    #ylim(-0.2,0.2)+
    geom_violin(color="black", position = dodge)+  
    facet_wrap(method ~ cells, scales = "free")+
    coord_flip()+
    scale_fill_manual(values =  mycolours)+
    xlab(TeX(" $log \\tilde{\\nu} - log \\nu $ "))+ geom_boxplot(width=0.3, outlier.colour=NA, position = dodge) +
    theme(axis.text.x = element_text(size = si, angle = 0, hjust = .5, vjust = .5, face = "plain", colour ="#3C5488FF" ),
        axis.text.y = element_text( size = si, angle = 0, hjust = 1, vjust = .0, face = "plain", colour ="#3C5488FF"),  
        axis.title.x = element_text( size = si, angle = 0, hjust = .5, vjust = 0, face = "plain", colour ="#3C5488FF"),
        axis.title.y = element_text( size = si, angle = 0, hjust = .5, vjust = .5, face = "plain", colour ="#3C5488FF"),
        legend.title = element_blank(),
       strip.background = element_rect(fill="#8491B44C"),
       strip.text.x = element_text(size = 12,colour = "#3C5488FF",face = "plain"),
        strip.text.y = element_text(size = 12,colour = "#3C5488FF",face = "plain"),
       axis.title.y.left = element_blank(),
       #legend.key.height = unit(5, "mm"),
        legend.text = element_text(color = "#3C5488FF",face ="italic" ),
        legend.position = "none")  # titl)

nu 
```


```{r}
dodge= position_dodge(width = 0.7)
lambda =ggplot(lambda.tot.plot,aes(x=cells, y=log(lambda_est)-log(lambda_real), fill=group)) + 
  facet_grid(method ~ ., scales = "free")+ 
    ylim(-0.75,0.75)+
    geom_violin(color="black", position = dodge)+  
    facet_wrap(method ~ cells, scales = "free")+
    coord_flip()+
    scale_fill_manual(values =  mycolours)+
  xlab(TeX(" $log \\tilde{\\lambda} - log \\lambda $ "))+ geom_boxplot(width=0.2, outlier.colour=NA, position = dodge)+
  theme(axis.text.x = element_text(size = si, angle = 0, hjust = .5, vjust = .5, face = "plain", colour ="#3C5488FF" ),
        axis.text.y = element_text( size = si, angle = 0, hjust = 1, vjust = .0, face = "plain", colour ="#3C5488FF"),  
        axis.title.x = element_text( size = si, angle = 0, hjust = .5, vjust = 0, face = "plain", colour ="#3C5488FF"),
        axis.title.y = element_text( size = si, angle = 0, hjust = .5, vjust = .5, face = "plain", colour ="#3C5488FF"),
        legend.title = element_blank(),
       strip.background = element_rect(fill="#8491B44C"),
       strip.text.x = element_text(size = 12,colour = "#3C5488FF",face = "plain"),
        strip.text.y = element_text(size = 12,colour = "#3C5488FF",face = "plain"),
       axis.title.y.left = element_blank(),
       #legend.key.height = unit(5, "mm"),
        legend.text = element_text(color = "#3C5488FF",face ="italic" ),
       legend.position = "right")
lambda
```
Percentage of a < 0 :

```{r}
print(a_table)
```




```{r}
sessionInfo()
```

